#!/bin/bash
# Auto-generated by deploy.yml -> init.sh handler
# This script ensures the dashboard index.html is generated before the container starts.

# Get domain from environment (set by deploy.yml)
if [ -f ".env" ]; then
  export $(grep -v '^#' .env | xargs)
fi

# Fallback
DOMAIN="${DOMAIN_NAME:-localhost}"

echo "🎨 Generating Dashboard for domain: $DOMAIN"
bash apps/dashboard/generate.sh "$DOMAIN"
